### ISSUE TITLE
显示锯齿问题

### ISSUE THREAD

**Issue by MoonWX** [vinceliuice/WhiteSur-kde#101]
我的桌面环境是Plasma 6.1.3，安装主题后上下面板均有锯齿，想问一下这是我的问题吗？
![2024-08-06_07-15](https://github.com/user-attachments/assets/5f33a6c0-da31-4fb3-8e03-e65128f15277)
![2024-08-06_07-15_1](https://github.com/user-attachments/assets/ca43209f-e488-4b2d-abe9-e65e349d90eb)

**Comment by vinceliuice** [comment]
会不会是显卡驱动问题阿

**Comment by MoonWX** [comment]
我在使用其他类似有圆角的主题时没有遇到过类似问题，我去试试更新一下显卡驱动

**Comment by vinceliuice** [comment]
其他主题没这个问题吗

**Comment by vinceliuice** [comment]
在github下载最新的更新试一试，现在应该没有问题了

**Comment by MoonWX** [comment]
下载最新的了，确定已经修复。感谢作者，好快的修复速度~~ξ( ✿＞◡❛)

**Comment by vinceliuice** [comment]
不客气
