### ISSUE TITLE
Low resolution icons in brightness and volume pop-ups

### ISSUE THREAD

**Issue by pders01** [vinceliuice/WhiteSur-kde#13]
![Screenshot from 2020-07-19 14-56-29](https://user-images.githubusercontent.com/49939682/87875236-3226b700-c9d0-11ea-8428-bdc7b4e9abaf.png)
![Screenshot from 2020-07-19 14-56-33](https://user-images.githubusercontent.com/49939682/87875237-32bf4d80-c9d0-11ea-9e99-6199af129483.png)

#### I love the theme and appreciate the effort but this issue really hurts the overall appearance.

If you think this is related to my low res screen (1366x768) please close this issue. I think these are svgs, but i haven't experienced this while using other gnome themes in the past.

**Comment by Teraskull** [comment]
Don't have this issue on a 1600x900 screen, so the problem is not with the icons.

**Comment by vinceliuice** [comment]
Icon theme issue

**Comment by pders01** [comment]
Was indeed an icon theme issue. I guess it was too hot last night..
