### ISSUE TITLE
In fractional scaling (like 1.25x) the window borders are very big, like this screenshot

### ISSUE THREAD

**Issue by Jontyshaw** [vinceliuice/WhiteSur-kde#15]
I have try to go to the "Application Style > Window Decorations" and set the boder to "Tiny", but it doesn't work
[](url)
![Screenshot_20200721_104004](https://user-images.githubusercontent.com/34794522/88014399-6b3a6500-cb51-11ea-863d-00550cd7465f.png)

**Comment by vinceliuice** [comment]
I'll add x1.5 and x2.0 version later

**Comment by Jontyshaw** [comment]
> I'll add x1.5 and x2.0 version later

😀Can you also add x1.25 version . I have tried mojave-x1.5 version, and the top border looks small than the application. My environment is manjaro kde and the fonts dpi is 125.
![Uploading 1.png…]()

**Comment by vinceliuice** [comment]
No problem!

**Comment by Jontyshaw** [comment]
> No problem!

Thank you

**Comment by vinceliuice** [comment]
I added them at last update, you can try it again

**Comment by Jontyshaw** [comment]
Kde store has not updated yet, can you tell me how to install it manually😂

**Comment by Jontyshaw** [comment]
> I added them at last update, you can try it again

I have install the new. It's all OK!  Thank you for your hard work

**Comment by vinceliuice** [comment]
You are welcome!

**Comment by Martinits** [comment]
Need a x1.75 version, too! That will be very nice for me.

**Comment by vinceliuice** [comment]
Added @Martinits @lenglingxuan

**Comment by Martinits** [comment]
Thanks a lot!
