### ISSUE TITLE
Can't read the results of krunner

### ISSUE THREAD

**Issue by cathaysia** [vinceliuice/WhiteSur-kde#17]
My font are white, and the panel of this theme have a opacity. Maybe we can consider a NO opacity's "plasma style"?

**Comment by vinceliuice** [comment]
Why not use the black font version

**Comment by cathaysia** [comment]
Maybe I can't change the color of font?

**Comment by vinceliuice** [comment]
Whitesur-alt is black font color version

**Comment by cathaysia** [comment]
Ok, thanks for your help. I guess this error maybe cause by discover. Now, I reinstall this theme through `osc-install`. It works fine.
