### ISSUE TITLE
Kwin crashes and than the design is wiped away

### ISSUE THREAD

**Issue by ibuntuos** [vinceliuice/WhiteSur-kde#28]
Hard to describe this really show stopping bug: Kwin tends to crash with the plasma thema activated when all windows are closed and you want to open for example dolphin - than for 2-3 seconds the whole transparancy and other theme settings are wiped like in the screenshot here:

![Bildschirmfoto von 2020-10-10 11-24-53](https://user-images.githubusercontent.com/68012153/95651556-80d58000-0aeb-11eb-97f8-da39eb5bc56a.png)

Main Problem is that if you are unlucky for reasons we couldn't figure out yet at a certain point the settings never won't come back. Uninstall of latte-dock or aurora and reinstall didn't solve the problem, complete remove of all the themes and reinstall them also didn't change anything. Even downloading other similar themes won't work anymore than. So basically the only thing you could do than is reinstall the whole system. 

We can't figure out the root cause for this. Did anyone had this issue similar before and resolved it not by a complete reset of the  entire system? We are close to our final build now and this really breaks us down since this is a major bug which needs to get adressed but we don't know where to start the investigation at all.

Thanks for any kind of help

BOfH

**Comment by D3SOX** [comment]
I had it a few times before that KWin crashed on me. However, my theme settings were not wiped.
In your screenshot it looks like it disabled the compositor after it crashed. Try pressing `CTRL`+`SHIFT`+`F12` to toggle the compositor.

**Comment by ibuntuos** [comment]
Thanks a lot, that was the solution i was searching for.
