### ISSUE TITLE
Wifi icon keeps oscillating

### ISSUE THREAD

**Issue by apandada1** [vinceliuice/WhiteSur-kde#3]
The wifi icon keeps oscillating between these two. Sometimes the change is induced by clicking on the icon.
Normal icon:
![Screenshot_20200701_135438](https://user-images.githubusercontent.com/3063132/86221499-83cbe680-bb74-11ea-9935-f5f5bfafdff3.png)
Wrong icon:
![Screenshot_20200701_134659](https://user-images.githubusercontent.com/3063132/86221508-862e4080-bb74-11ea-878c-d88f32168e5f.png)

Except a few small glitches like this, the theme is wonderful. 👍👍

**Comment by vinceliuice** [comment]
Thanks! I'll fix this

**Comment by Kandelai** [comment]
Yes, I am getting this as well with the new dark theme.

**Comment by vinceliuice** [comment]
Fixed now!

**Comment by Kandelai** [comment]
> Fixed now!

Thank you so much!!

**Comment by vinceliuice** [comment]
You are welcome!
