### ISSUE TITLE
Dark Analog Clock icon

### ISSUE THREAD

**Issue by aliquo93** [vinceliuice/WhiteSur-kde#35]
Hi, great theme, but could you please make the Analog Clock widget icon for the dark version of the theme, actually dark? Like the iOS dark clock widget icon: 

![iosclock](https://user-images.githubusercontent.com/9071297/106452451-2c825180-6488-11eb-85c3-adab6494ad0a.png)

**Comment by vinceliuice** [comment]
No peoblem!

**Comment by aliquo93** [comment]
Thank you! Just a curiosity, when you'll update it, I'll have to delete the theme from KDE settings and download it again or it will be automatically updated?

**Comment by vinceliuice** [comment]
You have to reinstall it

**Comment by aliquo93** [comment]
> You have to reinstall it

Ok, thanks! Can you please let me know here when you’ll update it?

**Comment by aliquo93** [comment]
Hi, I've updated it to the latest version but the clock is still white... didn't you change it yet?

**Comment by aliquo93** [comment]
Hi, a long time is passed, but the icon is still white.

**Comment by aliquo93** [comment]
Why you closed? I updated to latest version but the icon is still white... can you let me know something?

**Comment by vinceliuice** [comment]
Just download the last update it's fixed

**Comment by aliquo93** [comment]
I've updated it, but it's not completely black, as you can see in the screenshot below:

https://i.imgur.com/PIRNKTI.png

**Comment by aliquo93** [comment]
![clock](https://user-images.githubusercontent.com/9071297/125101535-9a3b4500-e0da-11eb-9a3f-566c0b9d89cf.png)
