### ISSUE TITLE
bad window decoration

### ISSUE THREAD

**Issue by BrianRuizy** [vinceliuice/WhiteSur-kde#36]
Seem to have bad margins on window decorations. 

Operating System: Manjaro Linux
KDE Plasma Version: 5.20.5
KDE Frameworks Version: 5.78.0
Qt Version: 5.15.2
Kernel Version: 5.9.16-1-MANJARO
OS Type: 64-bit
Processors: 12 × AMD Ryzen 5 3600 6-Core Processor
Memory: 15.6 GiB of RAM
Graphics Processor: GeForce RTX 2060 SUPER/PCIe/SSE2

![image](https://user-images.githubusercontent.com/23439187/107912563-575ab400-6f24-11eb-9aca-953a9e051eed.png)
![image](https://user-images.githubusercontent.com/23439187/107912655-8113db00-6f24-11eb-9b62-54daf88615d6.png)

**Comment by BrianRuizy** [comment]
seems to be duplicate of #23

**Comment by mehrdad-mixtape** [comment]
Hi everybody. I solved this problem!!!.
Just do:
1. sudo -s
2. vim or nano /etc/sddm.conf.d/kde_settings.conf
3. go down and find [x11] section.
4. if "ServerArguments = -dpi 0" change it to ServerArguments=-dpi 96
5. done!
6. 
![Screenshot_20220316_173154](https://user-images.githubusercontent.com/71973800/158607539-af43a8fe-0973-43b5-a64f-55a367ed6440.png)
It worked for me :).
main problem is between "nvidia-driver on perfomance mode" and "sddm display manager"
