### ISSUE TITLE
Visibility of KDE shell with light variant of theme

### ISSUE THREAD

**Issue by qurczax** [vinceliuice/WhiteSur-kde#39]
All the menus are difficult to read when something bright is behind it (screen). I suggest to change the font color to something darker.
![Screenshot_20210326_135852](https://user-images.githubusercontent.com/11503879/112635370-064fb100-8e3c-11eb-831c-8bfad705d9db.png)

**Comment by zeparu** [comment]
im pretty sure thats what the whitesur-alt theme is for

**Comment by qurczax** [comment]
ohh, I'm sorry. I didn't know about it. Now it's fine hahhah
