### ISSUE TITLE
install.sh not working? 

### ISSUE THREAD

**Issue by tejasag** [vinceliuice/WhiteSur-kde#45]
Hey there! I am pretty new to KDE Plasma and I have been using the White Sur theme previously on my gnome for a long time so I gave it a try on KDE too. But running install.sh doesn't change everything like the top bar and the dock et Cetra. Do I have to install separate extensions for them or something?

Thanks!

**Comment by vinceliuice** [comment]
This shell only install this theme, not change your desktop settings, you need to set it by yourself

**Comment by tejasag** [comment]
Alright. thanks!!
