### ISSUE TITLE
The downloaded package does not contain any useful meta information

### ISSUE THREAD

**Issue by madjoe** [vinceliuice/WhiteSur-kde#48]
Whilst trying to update the `Plasma Style` from my System Settings in Manjaro (right after successfully updated the `Global Theme`), the following message appears:

`The installation of /tmp/CONPgw-WhiteSur-dark.tar.gz failed, as the downloaded package does not contain any useful meta information, which means it is not a valid KPackage.`

The file `/tmp/CONPgw-WhiteSur-dark.tar.gz` fails to open with Ark.

```
$ cd /tmp && ls -al *WhiteSur*
.rw-r--r--  1843309 joe  joe   13 Jul 22:37  RNTruk-com.github.vinceliuice.WhiteSur-dark.tar.gz
.rw-r--r--   174112 joe  joe   13 Jul 22:40  Tkibbl-WhiteSur-dark.tar.gz
.rw-r--r--   174112 joe  joe   13 Jul 22:42  NcxMzy-WhiteSur-dark.tar.gz
.rw-r--r--   174112 joe  joe   13 Jul 22:43  CONPgw-WhiteSur-dark.tar.gz
```

**Comment by vinceliuice** [comment]
I changed it to tar.xz files, I don't know why it will get broken when I use tar.gz

**Comment by madjoe** [comment]
Now works like a charm. Perfect, thanks!
