### ISSUE TITLE
黑色主题窗体有阴影

### ISSUE THREAD

**Issue by imic07** [vinceliuice/WhiteSur-kde#50]
如图：重启也不能解决
![image](https://user-images.githubusercontent.com/16321067/125879997-ed595315-bd81-4fb3-8569-a06639cf8ac6.png)

**Comment by vinceliuice** [comment]
Kde de bug, 一直都有，你没开启透明模糊效果吗

**Comment by imic07** [comment]
> Kde de bug, 一直都有，你没开启透明模糊效果吗

是在这里配置吗？我都用的默认值
![image](https://user-images.githubusercontent.com/16321067/125881964-a6b630de-b97c-4df0-b6bb-c65b4e5555f8.png)
