### ISSUE TITLE
怎么进行状态栏样式调整

### ISSUE THREAD

**Issue by imic07** [vinceliuice/WhiteSur-kde#52]
状态栏默认有很多麻点点，很不好看.
![image](https://user-images.githubusercontent.com/16321067/125967605-d85e9d4c-b850-4b98-adae-8d1f0ca2424b.png)

当全屏打开浏览器等，此时发现状态栏/开始菜单中的麻点点消失了，样式挺好看的，如下图. 有没有办法设置默认的状态栏样式就是下面这样呢？
![image](https://user-images.githubusercontent.com/16321067/125967520-b9756c2b-cea6-4047-96d8-f4234832c98c.png)

**Comment by vinceliuice** [comment]
去窗口透明效果里把噪点拉到最低

**Comment by imic07** [comment]
确实有用.   工作区行为/桌面特效/窗口背景虚化/噪点
