### ISSUE TITLE
可以替换某些图标吗？

### ISSUE THREAD

**Issue by imic07** [vinceliuice/WhiteSur-kde#53]
比如有些图标我想去重新定义下，需要在哪个位置修改呢
![image](https://user-images.githubusercontent.com/16321067/126019188-fd0af4b4-4bc6-4748-8c55-565526565aff.png)

**Comment by vinceliuice** [comment]
https://github.com/vinceliuice/WhiteSur-icon-theme/

**Comment by vinceliuice** [comment]
运行 ./install.sh -a
