### ISSUE TITLE
Some UI elements have a solid black rectangle.

### ISSUE THREAD

**Issue by c-gaskell** [vinceliuice/WhiteSur-kde#55]
After updating to the latest version of Plasma and Latte, some UI elements now have these ugly black rectangles on them.
![image](https://user-images.githubusercontent.com/67276719/128259866-ea18ccab-736a-438e-9f22-212ef7fbe436.png)
![image](https://user-images.githubusercontent.com/67276719/128259996-cffb45da-567e-471a-944e-b728c49b1d39.png)

Versions:
```
plasma-desktop 5.22.4-1
latte-dock-git r5596.71f9e891-1
WhiteSur 0.4
```

**Comment by vinceliuice** [comment]
Download the last verion on github, this is fixed

**Comment by c-gaskell** [comment]
Awesome, thanks. Will the version on the KDE store be updated soon?

**Comment by vinceliuice** [comment]
No problem!
