### ISSUE TITLE
应用程序按钮不对应

### ISSUE THREAD

**Issue by Time-xg** [vinceliuice/WhiteSur-kde#62]
![Screenshot_20211221_225813](https://user-images.githubusercontent.com/34192060/146951599-8880184f-582e-4c4c-b981-d5ed2c2aff01.png)

如图绿色应该是最小化  黄色应该是最大化吧  这样让我很不适应

**Comment by vinceliuice** [comment]
你要不百度一下吧

**Comment by vinceliuice** [comment]
这个位置可以自己调的

**Comment by Time-xg** [comment]
> 这个位置可以自己调的

今天看了一下mac系统。 好像确实绿色的说最大化。黄色的是最小化。我的问题
