### ISSUE TITLE
An Error Occurred

### ISSUE THREAD

**Issue by StrangerGithuber** [vinceliuice/WhiteSur-kde#69]
Hi,
When I am trying to installing this then I get this error:
![image](https://user-images.githubusercontent.com/1939827/158032024-2b87d607-cd5d-443e-9b02-92d4afd4ed3d.png)

Maybe just me I get or other people too? Same thing with the dark version:
![image](https://user-images.githubusercontent.com/1939827/158031736-b0a0a3a8-f7be-4e1d-a644-b4b4b5ea83f0.png)

What I can do?

**Comment by vinceliuice** [comment]
Sddm need root permission

**Comment by StrangerGithuber** [comment]
Ah ok. Thank you. I will try then. 👍
