### ISSUE TITLE
add support for gtk apps

### ISSUE THREAD

**Issue by barfin** [vinceliuice/WhiteSur-kde#7]

**Comment by vinceliuice** [comment]
No problem!

**Comment by D1mon** [comment]
+1

**Comment by D3SOX** [comment]
What's the problem with https://github.com/vinceliuice/WhiteSur-gtk-theme ?

**Comment by barfin** [comment]
> What's the problem with https://github.com/vinceliuice/WhiteSur-gtk-theme ?

the problem is that the gtk release didn't exist when created this issue
