### ISSUE TITLE
[提问]dolphin在树状视图下面显示了蓝色的背景色,这如何修改?

### ISSUE THREAD

**Issue by a15355447898a** [vinceliuice/WhiteSur-kde#86]
![image](https://github.com/vinceliuice/WhiteSur-kde/assets/62456287/8b7f8229-f8cf-4640-9787-dff55ae44fba)

![image](https://github.com/vinceliuice/WhiteSur-kde/assets/62456287/6e35506c-c789-4c77-9743-b4ea1460bef7)

我想要树状视图下面也和第一张图一样,不要有蓝色的背景色

**Comment by appdev** [comment]
有同样的问题，这个颜色非常的突兀
