### ISSUE TITLE
The taskbar isn't themed correctly

### ISSUE THREAD

**Issue by ShadeZinc46** [vinceliuice/WhiteSur-kde#88]
I love the look of this theme, but the taskbar (dock, shortcut bar, whatever you wanna call it) is missing. I've searched the settings menu to see if it was simply disabled, but no. I have Kvantum installed. Here's a screenshot.

![image](https://github.com/vinceliuice/WhiteSur-kde/assets/72886318/2b459570-7526-40f1-a8a6-a7a46b4a2f70)

**Comment by vinceliuice** [comment]
Right click on desktop and add a default taskbar

**Comment by ShadeZinc46** [comment]
Ah, I see what you mean now. It still looks nothing like the pictures though 


![image](https://github.com/vinceliuice/WhiteSur-kde/assets/72886318/aa177e8c-c408-4b9a-8b03-b0109767e296)

**Comment by vinceliuice** [comment]
You mean the dock ? I'm using latte dock for the bottom taskbar

**Comment by ShadeZinc46** [comment]
Ahh, thank you. That worked.
