### ISSUE TITLE
Menus are offset when shadow is activated

### ISSUE THREAD

**Issue by Gpinchon** [vinceliuice/WhiteSur-kde#95]
I'm having issues with menu shadows when using Kvantum, when activated the menus are offset, it seems because the shadow is taken into account by KDE when rendering. When deactivating shadows the submenus are "overstepping" on top of each others.

![image](https://github.com/vinceliuice/WhiteSur-kde/assets/8039212/1814a890-1b7c-4564-89dc-967ebf11a5b8)

[ETA] setting menu_shadow_depth to 0 without deactivating shadow seems to "fix" this, but you lose the menu's shadows...

**Comment by vinceliuice** [comment]
I reduced the menu shadow depth for a temp fix, I think this is more like a kvantum issue

**Comment by Weather-OS** [comment]
This didn't fix it. I'm still encountering the same issue here
