### ISSUE TITLE
Some icons are missing

### ISSUE THREAD

**Issue by RashadGasimli** [vinceliuice/WhiteSur-kde#98]
Hello, some icons are missing on plasma 6. Here is some photos.

![Screenshot_20240513_090634](https://github.com/vinceliuice/WhiteSur-kde/assets/158089693/bda73616-c1b2-435d-b498-a5b478b92a9e)

![Screenshot_20240513_090637](https://github.com/vinceliuice/WhiteSur-kde/assets/158089693/2a4cbeb9-9521-47b9-a099-b3233ae117ec)

![Screenshot_20240513_090648](https://github.com/vinceliuice/WhiteSur-kde/assets/158089693/336efb4e-5cd0-40ca-9eae-1db85aea9848)

**Comment by vinceliuice** [comment]
Download the last whitesur icon theme, it's fixed now: https://github.com/vinceliuice/WhiteSur-icon-theme
